// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AI struct {
	Summary string `json:"summary"`
}

type BlobReference struct {
	Height  int             `json:"height"`
	Palette json.RawMessage `json:"palette"`
	Path    string          `json:"path"`
	Type    string          `json:"type"`
	Url     string          `json:"url"`
	Width   int             `json:"width"`
}

type Content struct {
	Body string `json:"body"`
	Type string `json:"type"`
}

type CreateObjectRequest struct {
	Content string          `json:"content"`
	Spaces  json.RawMessage `json:"spaces"`
	Tags    json.RawMessage `json:"tags"`
	Title   string          `json:"title"`
	Url     string          `json:"url"`
}

type Entity struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

type Object struct {
	Ai         json.RawMessage `json:"ai"`
	Blob       json.RawMessage `json:"blob"`
	Bumped     string          `json:"bumped"`
	Content    json.RawMessage `json:"content"`
	Created    string          `json:"created"`
	Deleted    string          `json:"deleted"`
	Entity     json.RawMessage `json:"entity"`
	Id         string          `json:"id"`
	Modified   string          `json:"modified"`
	Notes      json.RawMessage `json:"notes"`
	Screenshot json.RawMessage `json:"screenshot"`
	Source     json.RawMessage `json:"source"`
	Spaces     json.RawMessage `json:"spaces"`
	Summary    string          `json:"summary"`
	Tags       json.RawMessage `json:"tags"`
	Title      string          `json:"title"`
}

type ObjectNote struct {
	Content json.RawMessage `json:"content"`
	Id      string          `json:"id"`
}

type ObjectSource struct {
	Url string `json:"url"`
}

type ObjectSpace struct {
	Id string `json:"id"`
}

type ObjectTag struct {
	Flags int    `json:"flags"`
	Name  string `json:"name"`
}

type Palette struct {
}

type Problem struct {
	Detail   string `json:"detail"`
	Instance string `json:"instance"`
	Status   int    `json:"status"`
	Title    string `json:"title"`
	Type     string `json:"type"`
}

type Prose struct {
}

type SearchMatch struct {
	Id            string  `json:"id"`
	Score         float64 `json:"score"`
	SemanticScore float64 `json:"semanticScore"`
}

type Space struct {
	Color   string          `json:"color"`
	Created string          `json:"created"`
	Id      string          `json:"id"`
	Name    string          `json:"name"`
	Objects json.RawMessage `json:"objects"`
}

type Tag struct {
	Count    int    `json:"count"`
	Flags    int    `json:"flags"`
	Modified string `json:"modified"`
	Name     string `json:"name"`
}

type TagReference struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
