// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/nawwwal/mymind/internal/cli"
	"github.com/nawwwal/mymind/internal/client"
	"github.com/nawwwal/mymind/internal/cliutil"
	"github.com/nawwwal/mymind/internal/config"
	"github.com/nawwwal/mymind/internal/mcp/cobratree"
	"github.com/nawwwal/mymind/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("convert_content",
			mcplib.WithDescription("Converts between plain text, Markdown, and mymind prose. Source and target formats must differ. Returns the new Prose."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/convert", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("entities_get-entity",
			mcplib.WithDescription("WIP/coming soon. The docs say type identifiers, property shapes, and this endpoint may change before launch. Do not ship production integrations against this path yet. Required: id. Returns the Entity."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entities/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Search mymind objects. Returns useful result summaries with id, score, title, type, URL, tags, and dates when available. Required: q. Optional: limit (default: 20), semantic, semanticBoost, similarTo, rerank, matchesOnly."),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Search query.")),
			mcplib.WithString("limit", mcplib.Description("Maximum results to return.")),
			mcplib.WithString("semantic", mcplib.Description("Use semantic search.")),
			mcplib.WithString("semanticBoost", mcplib.Description("Multiplier applied only when semantic=true.")),
			mcplib.WithString("similarTo", mcplib.Description("Return objects related to this object ID. Mastermind only.")),
			mcplib.WithString("rerank", mcplib.Description("Use Mastermind reranking.")),
			mcplib.WithString("matchesOnly", mcplib.Description("Return raw ranked IDs without fetching object summaries.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeSearchAPIHandler(),
	)
	s.AddTool(
		mcplib.NewTool("objects_create",
			mcplib.WithDescription("Creates an object from exactly one of `url`, `content`, or multipart `blob`. Duplicate URL/content/blob saves return the existing object, refresh `bumped`, and respond with 200 instead of 201. Optional: content, spaces, tags (plus 2 more). Returns the new Object."),
			mcplib.WithString("content", mcplib.Description("Plain string or structured Content object.")),
			mcplib.WithString("spaces", mcplib.Description("Spaces")),
			mcplib.WithString("tags", mcplib.Description("Tags")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithString("url", mcplib.Description("Url")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects", []mcpParamBinding{{PublicName: "content", WireName: "content", Location: "body"}, {PublicName: "spaces", WireName: "spaces", Location: "body"}, {PublicName: "tags", WireName: "tags", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "url", WireName: "url", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("objects_delete",
			mcplib.WithDescription("Soft-deletes an object. Deleted objects are recoverable for 30 days. Required: id. Returns the DeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/objects/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_get",
			mcplib.WithDescription("Get an object. Required: id. Optional: contentAs. Returns the Object."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("contentAs", mcplib.Description("Convert returned object content to this format.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "contentAs", WireName: "contentAs", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_list",
			mcplib.WithDescription("Returns objects accessible to the authenticated key. If `q` is present, search semantics and search credit costs apply. Deleted objects are excluded. Optional: q, id, spaceId (plus 3 more)."),
			mcplib.WithString("q", mcplib.Description("Search query using the same syntax as `/search`.")),
			mcplib.WithString("id", mcplib.Description("Repeatable object IDs to fetch, e.g. `?id=a&id=b`.")),
			mcplib.WithString("spaceId", mcplib.Description("Restrict results to objects in one space.")),
			mcplib.WithString("similarTo", mcplib.Description("Return related objects ranked by similarity. Mastermind only.")),
			mcplib.WithString("contentAs", mcplib.Description("Convert returned object content to this format.")),
			mcplib.WithString("limit", mcplib.Description("Max results. Search queries are capped at 1000.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects", []mcpParamBinding{{PublicName: "q", WireName: "q", Location: "query"}, {PublicName: "id", WireName: "id", Location: "query"}, {PublicName: "spaceId", WireName: "spaceId", Location: "query"}, {PublicName: "similarTo", WireName: "similarTo", Location: "query"}, {PublicName: "contentAs", WireName: "contentAs", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("objects_update",
			mcplib.WithDescription("Update object metadata. Required: id. Optional: summary, title. Returns the updated UpdateResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("summary", mcplib.Description("User-editable summary.")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/objects/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "summary", WireName: "summary", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_blob_get-object",
			mcplib.WithDescription("Returns original uploaded bytes for single-blob objects. May return 302 to a signed CDN URL. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/blob", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_content_get-object",
			mcplib.WithDescription("Returns text-based object content in native or requested format. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/content", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_content_update-object",
			mcplib.WithDescription("Full-replaces the content body of a Note object. Returns 422 for other object types. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/objects/{id}/content", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_notes_create-object",
			mcplib.WithDescription("Appends a note. API stores up to 100 notes, but the app currently surfaces only `notes[0]`. Required: objectId. Returns the new CreateObjectResponse."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{objectId}/notes", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}}, []string{"objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_notes_delete-object",
			mcplib.WithDescription("Delete an object note. Required: objectId, noteId. Returns the DeleteObjectResponse. Destructive."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithString("noteId", mcplib.Required(), mcplib.Description("Note id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/objects/{objectId}/notes/{noteId}", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}, {PublicName: "noteId", WireName: "noteId", Location: "path"}}, []string{"objectId", "noteId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_notes_update-object",
			mcplib.WithDescription("Full-replaces an existing note body. Required: objectId, noteId. Returns the updated UpdateObjectResponse."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithString("noteId", mcplib.Required(), mcplib.Description("Note id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/objects/{objectId}/notes/{noteId}", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}, {PublicName: "noteId", WireName: "noteId", Location: "path"}}, []string{"objectId", "noteId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_pin_object",
			mcplib.WithDescription("Pin an object. Required: id. Optional: position. Returns the new ObjectResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("position", mcplib.Description("Zero-based top-of-mind slot.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{id}/pin", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "position", WireName: "position", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_pin_unpin-object",
			mcplib.WithDescription("Unpin an object. Required: id. Returns the UnpinObjectResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/objects/{id}/pin", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_restore_object",
			mcplib.WithDescription("Restore an object. Required: id. Returns the new ObjectResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{id}/restore", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_screenshot_get-object",
			mcplib.WithDescription("Returns screenshot bytes captured at save time. May return 302 to a signed CDN URL. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/screenshot", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_spaces_add-object",
			mcplib.WithDescription("Adds one object to one or more spaces. Objects may belong to at most 100 spaces. Required: objectId. Returns the new AddObjectResponse."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{objectId}/spaces", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}}, []string{"objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_tags_add-object",
			mcplib.WithDescription("Add tags to an object. Required: objectId, tags. Returns the new AddObjectResponse."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithString("tags", mcplib.Required(), mcplib.Description("Tags")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{objectId}/tags", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}, {PublicName: "tags", WireName: "tags", Location: "body"}}, []string{"objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_tags_remove-object",
			mcplib.WithDescription("Remove tags from an object. Required: objectId. Returns the RemoveObjectResponse. Destructive."),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/objects/{objectId}/tags", []mcpParamBinding{{PublicName: "objectId", WireName: "objectId", Location: "path"}}, []string{"objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("objects_thumbnail_get-object",
			mcplib.WithDescription("Get object thumbnail. Required: id. Optional: size."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("size", mcplib.Description("Bounding box as WxH. Preserves aspect ratio like `object-fit: contain`.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/thumbnail", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "size", WireName: "size", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_create",
			mcplib.WithDescription("Create a space. Required: name. Optional: color. Returns the new Space."),
			mcplib.WithString("color", mcplib.Description("CSS color value, usually a hex code.")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Unique display name.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/spaces", []mcpParamBinding{{PublicName: "color", WireName: "color", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_delete",
			mcplib.WithDescription("Deletes the space; objects inside are not deleted. Required: id. Returns the DeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/spaces/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_get",
			mcplib.WithDescription("Get a space. Required: id. Returns the Space."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/spaces/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_list",
			mcplib.WithDescription("List spaces. Returns array of Space."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/spaces", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_update",
			mcplib.WithDescription("Update a space. Required: id. Optional: color, name. Returns the updated Space."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("color", mcplib.Description("CSS color value, usually a hex code.")),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/spaces/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "color", WireName: "color", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_objects_add-to-space",
			mcplib.WithDescription("Add an object to a space. Required: spaceId, objectId. Returns the updated AddToSpaceResponse."),
			mcplib.WithString("spaceId", mcplib.Required(), mcplib.Description("Space id")),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/spaces/{spaceId}/objects/{objectId}", []mcpParamBinding{{PublicName: "spaceId", WireName: "spaceId", Location: "path"}, {PublicName: "objectId", WireName: "objectId", Location: "path"}}, []string{"spaceId", "objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("spaces_objects_remove-from-space",
			mcplib.WithDescription("Remove an object from a space. Required: spaceId, objectId. Returns the RemoveFromSpaceResponse. Destructive."),
			mcplib.WithString("spaceId", mcplib.Required(), mcplib.Description("Space id")),
			mcplib.WithString("objectId", mcplib.Required(), mcplib.Description("Object id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/spaces/{spaceId}/objects/{objectId}", []mcpParamBinding{{PublicName: "spaceId", WireName: "spaceId", Location: "path"}, {PublicName: "objectId", WireName: "objectId", Location: "path"}}, []string{"spaceId", "objectId"}),
	)
	s.AddTool(
		mcplib.NewTool("tags_list",
			mcplib.WithDescription("Tags are created implicitly when first used; there is no standalone create tag endpoint. Optional: limit (default: 1000). Returns array of Tag."),
			mcplib.WithString("limit", mcplib.Description("Limit")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tags", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("local_search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT only). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

func truthyArg(args map[string]any, name string) bool {
	v, ok := args[name]
	if !ok {
		return false
	}
	switch value := v.(type) {
	case bool:
		return value
	case string:
		switch strings.ToLower(strings.TrimSpace(value)) {
		case "1", "true", "t", "yes", "y":
			return true
		}
	}
	return false
}

func makeSearchAPIHandler() server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		_ = ctx
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		args := req.GetArguments()
		query, ok := args["q"]
		if !ok || strings.TrimSpace(fmt.Sprintf("%v", query)) == "" {
			return mcplib.NewToolResultError("q is required"), nil
		}

		params := map[string]string{
			"q": fmt.Sprintf("%v", query),
		}
		for _, name := range []string{"limit", "semantic", "semanticBoost", "similarTo", "rerank"} {
			if v, ok := args[name]; ok {
				params[name] = fmt.Sprintf("%v", v)
			}
		}

		data, err := c.Get("/search", params)
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		items := cli.ExtractSearchResults(data)
		mode := "summaries"
		if truthyArg(args, "matchesOnly") {
			mode = "matches"
		} else {
			items = cli.HydrateSearchResults(c, items)
			items = cli.SummarizeSearchResults(items)
		}

		out, _ := json.Marshal(map[string]any{
			"count":  len(items),
			"items":  items,
			"mode":   mode,
			"source": "live",
		})
		return mcplib.NewToolResultText(string(out)), nil
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export MYMIND_KID=<kid> MYMIND_SECRET=<base64-secret>" +
					"\n      Run 'mymind doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your access key." +
					"\n      Set it with: export MYMIND_KID=<kid> MYMIND_SECRET=<base64-secret>" +
					"\n      Run 'mymind doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export MYMIND_KID=<kid> MYMIND_SECRET=<base64-secret>" +
					"\n      Run 'mymind doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "mymind", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "mymind", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenWithContext(ctx, dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(map[string]any{
		"count":  len(results),
		"items":  results,
		"mode":   "local",
		"source": "local",
	}, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	// Block write operations
	upper := strings.ToUpper(strings.TrimSpace(query))
	for _, prefix := range []string{"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE"} {
		if strings.HasPrefix(upper, prefix) {
			return mcplib.NewToolResultError("only SELECT queries are allowed"), nil
		}
	}

	db, err := store.OpenWithContext(ctx, dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "mymind",
		"description": "The mymind API uses signed per-request JWT bearer tokens. Objects are saved URLs, notes, images, documents, videos,...",
		"archetype":   "content",
		"tool_count":  30,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion mymind binary.",
		"auth": map[string]any{
			"type": "mymind_hs256_request_jwt",
			"env_vars": []map[string]any{
				{
					"name":        "MYMIND_KID",
					"kind":        "key_id",
					"required":    true,
					"sensitive":   true,
					"description": "mymind access key identifier.",
				},
				{
					"name":        "MYMIND_SECRET",
					"kind":        "shared_secret",
					"required":    true,
					"sensitive":   true,
					"description": "base64-encoded mymind access key secret; used to sign each request JWT.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "convert",
				"description": "Manage convert",
				"endpoints":   []string{"content"},
			},
			{
				"name":        "entities",
				"description": "Manage entities",
				"endpoints":   []string{"get-entity"},
				"searchable":  true,
			},
			{
				"name":        "objects",
				"description": "Manage objects",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "spaces",
				"description": "Manage spaces",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tags",
				"description": "Manage tags",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Call context first when you do not know the surface.",
			"Use search first for finding saved objects. It returns useful summaries with id, score, title, type, URL, tags, and dates when available.",
			"Use matchesOnly=true only when you need raw ranked IDs.",
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
