// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectsThumbnailCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "thumbnail",
		Short: "Manage thumbnail",
	}

	cmd.AddCommand(newObjectsThumbnailGetObjectCmd(flags))
	return cmd
}
