// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectsBlobCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "blob",
		Short: "Manage blob",
	}

	cmd.AddCommand(newObjectsBlobGetObjectCmd(flags))
	return cmd
}
