// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newObjectsListCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagId string
	var flagSpaceId string
	var flagSimilarTo string
	var flagContentAs string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns objects accessible to the authenticated key. If `q` is present, search semantics and search credit costs...",
		Example:     "  mymind objects list",
		Annotations: map[string]string{"pp:endpoint": "objects.list", "pp:method": "GET", "pp:path": "/objects", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("content-as") {
				allowedContentAs := []string{"text/markdown"}
				validContentAs := false
				for _, v := range allowedContentAs {
					if flagContentAs == v {
						validContentAs = true
						break
					}
				}
				if !validContentAs {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "content-as", flagContentAs, allowedContentAs)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/objects"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "objects", path, map[string]string{
				"q":         fmt.Sprintf("%v", flagQ),
				"id":        fmt.Sprintf("%v", flagId),
				"spaceId":   fmt.Sprintf("%v", flagSpaceId),
				"similarTo": fmt.Sprintf("%v", flagSimilarTo),
				"contentAs": fmt.Sprintf("%v", flagContentAs),
				"limit":     fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Search query using the same syntax as `/search`.")
	cmd.Flags().StringVar(&flagId, "id", "", "Repeatable object IDs to fetch, e.g. `?id=a&id=b`.")
	cmd.Flags().StringVar(&flagSpaceId, "space-id", "", "Restrict results to objects in one space.")
	cmd.Flags().StringVar(&flagSimilarTo, "similar-to", "", "Return related objects ranked by similarity. Mastermind only.")
	cmd.Flags().StringVar(&flagContentAs, "content-as", "", "Convert returned object content to this format. (one of: text/markdown)")
	cmd.Flags().IntVar(&flagLimit, "limit", 10000, "Max results. Search queries are capped at 1000.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
