// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "objects",
		Short: "Manage objects",
	}

	cmd.AddCommand(newObjectsCreateCmd(flags))
	cmd.AddCommand(newObjectsDeleteCmd(flags))
	cmd.AddCommand(newObjectsGetCmd(flags))
	cmd.AddCommand(newObjectsListCmd(flags))
	cmd.AddCommand(newObjectsUpdateCmd(flags))
	cmd.AddCommand(newObjectsBlobCmd(flags))
	cmd.AddCommand(newObjectsContentCmd(flags))
	cmd.AddCommand(newObjectsNotesCmd(flags))
	cmd.AddCommand(newObjectsPinCmd(flags))
	cmd.AddCommand(newObjectsRestoreCmd(flags))
	cmd.AddCommand(newObjectsScreenshotCmd(flags))
	cmd.AddCommand(newObjectsSpacesCmd(flags))
	cmd.AddCommand(newObjectsTagsCmd(flags))
	cmd.AddCommand(newObjectsThumbnailCmd(flags))
	return cmd
}
