// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMymindSearchPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagLimit int
	var flagSemantic bool
	var flagSemanticBoost float64
	var flagSimilarTo string
	var flagRerank bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "mymind-search",
		Short:       "Search with Lucene-inspired syntax, optional semantic search, related-object matching, and Mastermind-only reranking.",
		Long:        "Shortcut for 'mymind-search search-objects'. Search with Lucene-inspired syntax, optional semantic search, related-object matching, and Mastermind-only reranking.",
		Example:     "  mymind mymind-search --q example-value",
		Annotations: map[string]string{"pp:endpoint": "mymind-search.search-objects", "pp:method": "GET", "pp:path": "/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("q") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "q")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/search"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "mymind-search", path, map[string]string{
				"q":             fmt.Sprintf("%v", flagQ),
				"limit":         fmt.Sprintf("%v", flagLimit),
				"semantic":      fmt.Sprintf("%v", flagSemantic),
				"semanticBoost": fmt.Sprintf("%v", flagSemanticBoost),
				"similarTo":     fmt.Sprintf("%v", flagSimilarTo),
				"rerank":        fmt.Sprintf("%v", flagRerank),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Query string. URL-encode operators such as `&&` and `:`.")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Limit")
	cmd.Flags().BoolVar(&flagSemantic, "semantic", false, "Semantic")
	cmd.Flags().Float64Var(&flagSemanticBoost, "semantic-boost", 0.0, "Multiplier applied only when `semantic=true`.")
	cmd.Flags().StringVar(&flagSimilarTo, "similar-to", "", "Mastermind-only related-object search. Implies semantic search.")
	cmd.Flags().BoolVar(&flagRerank, "rerank", false, "Mastermind-only cross-encoder rerank. Implies semantic search and caps results at 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
