// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"reflect"
	"testing"
)

func TestExtractSearchResults_UnwrapsMatchesEnvelope(t *testing.T) {
	data := json.RawMessage(`{
		"elapsed": 0,
		"count": 2,
		"query": "skills",
		"matches": [
			{"id": "obj_1", "score": 53.5},
			{"id": "obj_2", "score": 47.3}
		]
	}`)

	results := extractSearchResults(data)

	if len(results) != 2 {
		t.Fatalf("expected 2 matches, got %d: %s", len(results), results)
	}
	for i, result := range results {
		if isNilOrEmpty(result) {
			t.Fatalf("result %d should survive search output filtering: %s", i, result)
		}
	}
}

func TestParseStringListFlag_AcceptsCommaSeparatedValues(t *testing.T) {
	got, err := parseStringListFlag("reading,research")
	if err != nil {
		t.Fatalf("parseStringListFlag returned error: %v", err)
	}
	want := []string{"reading", "research"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("expected %#v, got %#v", want, got)
	}
}

func TestParseStringListFlag_PreservesJSONArrayValues(t *testing.T) {
	got, err := parseStringListFlag(`["reading","research"]`)
	if err != nil {
		t.Fatalf("parseStringListFlag returned error: %v", err)
	}
	want := []any{"reading", "research"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("expected %#v, got %#v", want, got)
	}
}
