// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/nawwwal/mymind/internal/client"
	"github.com/nawwwal/mymind/internal/store"
	"github.com/spf13/cobra"
)

// isNilOrEmpty checks whether a JSON object has nil or empty values for
// common identifier fields (title, name, identifier, id).
// Also checks nested "document" objects for search result wrappers.
func isNilOrEmpty(raw json.RawMessage) bool {
	var obj map[string]interface{}
	if err := json.Unmarshal(raw, &obj); err != nil {
		return true
	}
	// Check top-level fields
	for _, key := range []string{"title", "name", "identifier", "id"} {
		if v, ok := obj[key]; ok {
			if v == nil {
				continue
			}
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				return false
			}
			// Non-string, non-nil value (e.g. numeric ID) — keep it
			if _, ok := v.(string); !ok {
				return false
			}
		}
	}
	// Check nested "document" for search result wrappers like {score, document: {name, ...}}
	if doc, ok := obj["document"]; ok {
		if docMap, ok := doc.(map[string]interface{}); ok {
			for _, key := range []string{"title", "name", "identifier", "id", "slug"} {
				if v, ok := docMap[key]; ok && v != nil {
					if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
						return false
					}
					if _, ok := v.(string); !ok {
						return false
					}
				}
			}
		}
	}
	// If the object has a "score" field, it's likely a search result — keep it
	if _, ok := obj["score"]; ok {
		return false
	}
	return true
}

// extractSearchResults unwraps API search responses by checking common envelope paths.
func extractSearchResults(data json.RawMessage) []json.RawMessage {
	// Try direct array first
	var items []json.RawMessage
	if json.Unmarshal(data, &items) == nil {
		return items
	}
	// Try common wrapper paths: data, results, items
	var wrapped map[string]json.RawMessage
	if json.Unmarshal(data, &wrapped) == nil {
		for _, key := range []string{"matches", "data", "results", "items", "records", "entries"} {
			if inner, ok := wrapped[key]; ok {
				if json.Unmarshal(inner, &items) == nil {
					return items
				}
			}
		}
	}
	// Return as single-item array
	return []json.RawMessage{data}
}

// ExtractSearchResults unwraps API search responses for agent-facing callers.
func ExtractSearchResults(data json.RawMessage) []json.RawMessage {
	return extractSearchResults(data)
}

func searchResultID(raw json.RawMessage) string {
	var obj map[string]any
	if err := json.Unmarshal(raw, &obj); err != nil {
		return ""
	}
	if id, ok := obj["id"].(string); ok {
		return id
	}
	if doc, ok := obj["document"].(map[string]any); ok {
		if id, ok := doc["id"].(string); ok {
			return id
		}
	}
	return ""
}

func searchStringField(obj map[string]any, names ...string) string {
	for _, name := range names {
		if value, ok := obj[name]; ok {
			if s, ok := value.(string); ok && strings.TrimSpace(s) != "" {
				return s
			}
		}
	}
	return ""
}

func searchNestedStringField(obj map[string]any, parent string, names ...string) string {
	nested, ok := obj[parent].(map[string]any)
	if !ok {
		return ""
	}
	return searchStringField(nested, names...)
}

func searchTags(obj map[string]any) []string {
	rawTags, ok := obj["tags"].([]any)
	if !ok {
		return nil
	}
	tags := make([]string, 0, len(rawTags))
	for _, rawTag := range rawTags {
		switch tag := rawTag.(type) {
		case string:
			if strings.TrimSpace(tag) != "" {
				tags = append(tags, tag)
			}
		case map[string]any:
			if name := searchStringField(tag, "name", "title", "label"); name != "" {
				tags = append(tags, name)
			}
		}
	}
	return tags
}

func summarizeSearchResult(matchObj map[string]any, sourceObj map[string]any) map[string]any {
	result := map[string]any{}
	for _, key := range []string{"id", "score", "semanticScore"} {
		if value, ok := matchObj[key]; ok {
			result[key] = value
		}
	}
	if id, ok := sourceObj["id"]; ok {
		result["id"] = id
	}
	if title := searchStringField(sourceObj, "title", "name", "label"); title != "" {
		result["title"] = title
	}
	if entityType := searchStringField(sourceObj, "entityType", "type", "kind"); entityType != "" {
		result["type"] = entityType
	}
	if summary := searchStringField(sourceObj, "summary", "description"); summary != "" {
		result["summary"] = summary
	} else if body := searchNestedStringField(sourceObj, "content", "body", "text"); body != "" {
		result["summary"] = truncate(body, 240)
	}
	if url := searchNestedStringField(sourceObj, "source", "url"); url != "" {
		result["url"] = url
	} else if url := searchStringField(sourceObj, "url"); url != "" {
		result["url"] = url
	}
	if tags := searchTags(sourceObj); len(tags) > 0 {
		result["tags"] = tags
	}
	for _, key := range []string{"created", "modified", "bumped", "created_at", "updated_at"} {
		if value, ok := sourceObj[key]; ok {
			result[key] = value
		}
	}
	if highlights, ok := matchObj["highlights"]; ok {
		result["highlights"] = highlights
	}
	if matched, ok := matchObj["matched"]; ok {
		result["matched"] = matched
	}
	if hydrationStatus, ok := matchObj["hydration_status"]; ok {
		result["hydration_status"] = hydrationStatus
	}
	if hydrationError, ok := matchObj["hydration_error"]; ok {
		result["hydration_error"] = hydrationError
	}
	if len(result) == 0 {
		return matchObj
	}
	return result
}

func summarizeSearchMatch(match json.RawMessage) json.RawMessage {
	var matchObj map[string]any
	if err := json.Unmarshal(match, &matchObj); err != nil {
		return match
	}
	sourceObj := matchObj
	if doc, ok := matchObj["document"].(map[string]any); ok {
		sourceObj = doc
	}
	summary, err := json.Marshal(summarizeSearchResult(matchObj, sourceObj))
	if err != nil {
		return match
	}
	return summary
}

func mergeSearchMatchWithObject(match json.RawMessage, object json.RawMessage) json.RawMessage {
	var matchObj map[string]any
	if err := json.Unmarshal(match, &matchObj); err != nil {
		return summarizeSearchMatch(object)
	}
	var objectObj map[string]any
	if err := json.Unmarshal(object, &objectObj); err != nil {
		return summarizeSearchMatch(match)
	}
	merged, err := json.Marshal(summarizeSearchResult(matchObj, objectObj))
	if err != nil {
		return object
	}
	return merged
}

func annotateSearchHydrationError(match json.RawMessage, err error) json.RawMessage {
	var obj map[string]any
	if json.Unmarshal(match, &obj) != nil {
		return match
	}
	obj["hydration_status"] = "failed"
	obj["hydration_error"] = err.Error()
	annotated, marshalErr := json.Marshal(obj)
	if marshalErr != nil {
		return match
	}
	return annotated
}

func hydrateSearchResults(c *client.Client, matches []json.RawMessage) []json.RawMessage {
	results := make([]json.RawMessage, 0, len(matches))
	for _, match := range matches {
		id := searchResultID(match)
		if id == "" {
			results = append(results, summarizeSearchMatch(match))
			continue
		}
		object, err := c.Get("/objects/"+id, nil)
		if err != nil {
			results = append(results, annotateSearchHydrationError(match, err))
			continue
		}
		results = append(results, mergeSearchMatchWithObject(match, object))
	}
	return results
}

// HydrateSearchResults fetches object details for search matches and returns
// compact summaries instead of full object payloads.
func HydrateSearchResults(c *client.Client, matches []json.RawMessage) []json.RawMessage {
	return hydrateSearchResults(c, matches)
}

func summarizeSearchResults(results []json.RawMessage) []json.RawMessage {
	summaries := make([]json.RawMessage, 0, len(results))
	for _, result := range results {
		summaries = append(summaries, summarizeSearchMatch(result))
	}
	return summaries
}

// SummarizeSearchResults normalizes raw search matches or objects into the
// compact result shape used by CLI and MCP search surfaces.
func SummarizeSearchResults(results []json.RawMessage) []json.RawMessage {
	return summarizeSearchResults(results)
}

func newSearchCmd(flags *rootFlags) *cobra.Command {
	var resourceType string
	var limit int
	var dbPath string
	var semantic bool
	var semanticBoost float64
	var similarTo string
	var rerank bool
	var matchesOnly bool

	cmd := &cobra.Command{
		Use:   "search <query>",
		Short: "Full-text search across synced data or live API",
		Long: `Search data using FTS5 full-text search on locally synced data,
or hit the API's search endpoint when available.

In auto mode (default): uses the API search endpoint if the API has one,
otherwise searches local data. Falls back to local on network failure.
In live mode: uses the API search endpoint only.
In local mode: searches locally synced data only.

Default output is a useful result summary: id, score, title, type, URL,
tags, and dates when available. Use --matches-only only when an agent
needs the raw ranked IDs from the search endpoint.`,
		Example: `  # Search (uses API endpoint if available, local FTS otherwise)
  mymind search "error timeout"

  # Force local search only
  mymind search "payment failed" --data-source local

  # Search a specific resource type locally
  mymind search "critical" --type transactions --data-source local

  # Use semantic search and reranking on the live API
  mymind search "article about memory" --semantic --rerank

  # JSON output for piping
  mymind search "critical" --json --limit 20

  # Agent-safe search summary with only the fields you need
  mymind search "renewal notes" --agent --select id,title,url,score

  # Raw ranked IDs only
  mymind search "renewal notes" --matches-only --json`,
		Annotations: map[string]string{"mcp:hidden": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			query := args[0]
			// This API has a search endpoint: GET /search
			if flags.dataSource != "local" {
				c, err := flags.newClient()
				if err != nil {
					return err
				}
				queryParams := map[string]string{
					"q":             query,
					"limit":         fmt.Sprintf("%d", limit),
					"semantic":      fmt.Sprintf("%t", semantic),
					"semanticBoost": fmt.Sprintf("%v", semanticBoost),
					"similarTo":     similarTo,
					"rerank":        fmt.Sprintf("%t", rerank),
				}
				emitSearchStatus(cmd, flags, "Searching...")
				data, getErr := c.Get("/search", queryParams)
				if getErr == nil {
					// Live search succeeded
					results := extractSearchResults(data)
					if !matchesOnly {
						emitSearchStatus(cmd, flags, "Fetching result details...")
						results = hydrateSearchResults(c, results)
					}
					prov := DataProvenance{Source: "live"}
					return outputSearchResults(cmd, flags, results, limit, prov)
				}
				// Check if it's a network error for auto-mode fallback
				if flags.dataSource == "live" || !isNetworkError(getErr) {
					return classifyAPIError(getErr, flags)
				}
				// auto mode + network error: fall through to local FTS
				emitSearchFallbackStatus(cmd, flags)
			}

			// Local FTS search
			if dbPath == "" {
				dbPath = defaultDBPath("mymind")
			}

			db, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening local database: %w\nRun 'mymind sync' first to populate the local database.", err)
			}
			defer db.Close()

			var results []json.RawMessage
			emitSearchStatus(cmd, flags, "Searching local archive...")
			switch resourceType {
			case "objects":
				results, err = db.SearchObjects(query, limit)
			case "":
				// Search all FTS-enabled tables individually to avoid duplicates.
				seen := make(map[string]bool)
				_ = seen // prevent unused error when no FTS tables exist
				{
					partial, searchErr := db.SearchObjects(query, limit)
					if searchErr != nil {
						return fmt.Errorf("search objects failed: %w", searchErr)
					}
					for _, r := range partial {
						key := string(r)
						if !seen[key] {
							seen[key] = true
							results = append(results, r)
						}
					}
				}
			default:
				// Unrecognized type — fall back to generic search
				results, err = db.Search(query, limit)
			}
			if err != nil {
				return fmt.Errorf("search failed: %w", err)
			}

			reason := "user_requested"
			if flags.dataSource == "auto" {
				reason = "api_unreachable"
			}
			prov := localProvenance(db, "search", reason)

			return outputSearchResults(cmd, flags, results, limit, prov)
		},
	}

	cmd.Flags().StringVar(&resourceType, "type", "", "Filter by resource type")
	cmd.Flags().IntVar(&limit, "limit", 50, "Maximum results to return")
	cmd.Flags().BoolVar(&semantic, "semantic", false, "Use semantic search on the live API")
	cmd.Flags().Float64Var(&semanticBoost, "semantic-boost", 0.0, "Multiplier applied only when --semantic is set")
	cmd.Flags().StringVar(&similarTo, "similar-to", "", "Return objects related to this object ID on the live API")
	cmd.Flags().BoolVar(&rerank, "rerank", false, "Use Mastermind reranking on the live API")
	cmd.Flags().BoolVar(&matchesOnly, "matches-only", false, "Return raw search matches without fetching object details")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/mymind/data.db)")

	return cmd
}

func searchStatusEnabled(flags *rootFlags, stdoutTTY, stderrTTY bool, getenv func(string) string) bool {
	if flags == nil {
		return false
	}
	if flags.asJSON || flags.agent || flags.compact || flags.csv || flags.quiet {
		return false
	}
	if !stdoutTTY || !stderrTTY {
		return false
	}
	if getenv("CI") != "" || getenv("TERM") == "dumb" {
		return false
	}
	return true
}

func searchFallbackStatusMessage(flags *rootFlags, stdoutTTY, stderrTTY bool, getenv func(string) string) string {
	if !searchStatusEnabled(flags, stdoutTTY, stderrTTY, getenv) {
		return ""
	}
	return "API unreachable, falling back to local search."
}

func emitSearchFallbackStatus(cmd *cobra.Command, flags *rootFlags) {
	message := searchFallbackStatusMessage(
		flags,
		isTerminal(cmd.OutOrStdout()),
		isTerminal(cmd.ErrOrStderr()),
		os.Getenv,
	)
	emitSearchStatus(cmd, flags, message)
}

func emitSearchStatus(cmd *cobra.Command, flags *rootFlags, message string) {
	if message == "" {
		return
	}
	if searchStatusEnabled(flags, isTerminal(cmd.OutOrStdout()), isTerminal(cmd.ErrOrStderr()), os.Getenv) {
		fmt.Fprintln(cmd.ErrOrStderr(), message)
	}
}

// outputSearchResults filters, counts, and outputs search results with provenance.
func outputSearchResults(cmd *cobra.Command, flags *rootFlags, results []json.RawMessage, limit int, prov DataProvenance) error {
	// Filter out entries with nil or empty identifier fields.
	filtered := make([]json.RawMessage, 0, len(results))
	for _, r := range summarizeSearchResults(results) {
		if !isNilOrEmpty(r) {
			filtered = append(filtered, r)
		}
	}
	results = filtered

	// Enforce limit across aggregated results.
	if len(results) > limit {
		results = results[:limit]
	}

	if flags.quiet {
		return nil
	}

	machineMode := flags.asJSON || flags.compact || flags.csv || !isTerminal(cmd.OutOrStdout())

	// JSON mode always emits a valid envelope, including on no matches —
	// agents pipe stdout through json.loads / jq and need parseable output
	// regardless of result count. The filtered slice is built via make
	// above, so it's non-nil even when empty; json.Marshal renders that
	// as `[]` rather than `null`.
	if machineMode {
		data, err := json.Marshal(results)
		if err != nil {
			return err
		}
		if flags.selectFields != "" {
			data = filterFields(data, flags.selectFields)
		} else if flags.compact {
			data = compactFields(data)
		}
		if flags.csv {
			return printCSV(cmd.OutOrStdout(), data)
		}
		wrapped, err := wrapWithProvenance(data, prov)
		if err != nil {
			return err
		}
		return printOutput(cmd.OutOrStdout(), wrapped, true)
	}

	if len(results) == 0 {
		fmt.Fprintf(cmd.ErrOrStderr(), "No results (source: %s)\n", prov.Source)
		return nil
	}

	printProvenance(cmd, len(results), prov)
	return formatSearchHumanResults(cmd.OutOrStdout(), results)
}

func formatSearchHumanResults(w io.Writer, results []json.RawMessage) error {
	for i, raw := range results {
		if i > 0 {
			fmt.Fprintln(w)
		}
		var result map[string]any
		if err := json.Unmarshal(raw, &result); err != nil {
			return err
		}
		title := searchStringField(result, "title", "name", "label", "id")
		if title != "" {
			fmt.Fprintln(w, title)
		}
		writeSearchHumanField(w, "Score", result["score"])
		writeSearchHumanField(w, "Type", firstSearchValue(result, "type", "entityType", "kind"))
		writeSearchHumanField(w, "URL", firstSearchValue(result, "url"))
		writeSearchHumanField(w, "Summary", firstSearchValue(result, "summary", "description"))
		writeSearchHumanField(w, "Tags", result["tags"])
		writeSearchHumanField(w, "Created", firstSearchValue(result, "created", "created_at"))
		writeSearchHumanField(w, "Modified", firstSearchValue(result, "modified", "updated_at", "bumped"))
		writeSearchHumanField(w, "Hydration error", result["hydration_error"])
	}
	return nil
}

func firstSearchValue(obj map[string]any, keys ...string) any {
	for _, key := range keys {
		if value, ok := obj[key]; ok {
			return value
		}
	}
	return nil
}

func writeSearchHumanField(w io.Writer, label string, value any) {
	formatted := formatSearchHumanValue(value)
	if formatted == "" {
		return
	}
	fmt.Fprintf(w, "  %s: %s\n", label, formatted)
}

func formatSearchHumanValue(value any) string {
	switch v := value.(type) {
	case string:
		if strings.TrimSpace(v) == "" {
			return ""
		}
		if len(v) >= 19 && v[4] == '-' && v[7] == '-' && v[10] == 'T' {
			return v[:10]
		}
		return v
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v))
		}
		return fmt.Sprintf("%.2f", v)
	case bool:
		return fmt.Sprintf("%t", v)
	case []any:
		parts := make([]string, 0, len(v))
		for _, item := range v {
			if formatted := formatSearchHumanValue(item); formatted != "" {
				parts = append(parts, formatted)
			}
		}
		return strings.Join(parts, ", ")
	case map[string]any:
		if name := searchStringField(v, "name", "title", "label", "id"); name != "" {
			return name
		}
		data, _ := json.Marshal(v)
		return string(data)
	case nil:
		return ""
	default:
		data, _ := json.Marshal(v)
		return string(data)
	}
}

func mustMarshalSearchResults(results []json.RawMessage) json.RawMessage {
	data, err := json.Marshal(results)
	if err != nil {
		return nil
	}
	return data
}
