// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func mustJSON(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func TestExtractSearchResults_UnwrapsMatchesEnvelope(t *testing.T) {
	data := json.RawMessage(`{
		"elapsed": 0,
		"count": 2,
		"query": "skills",
		"matches": [
			{"id": "obj_1", "score": 53.5},
			{"id": "obj_2", "score": 47.3}
		]
	}`)

	results := extractSearchResults(data)

	if len(results) != 2 {
		t.Fatalf("expected 2 matches, got %d: %s", len(results), results)
	}
	for i, result := range results {
		if isNilOrEmpty(result) {
			t.Fatalf("result %d should survive search output filtering: %s", i, result)
		}
	}
}

func TestParseStringListFlag_AcceptsCommaSeparatedValues(t *testing.T) {
	got, err := parseStringListFlag("reading,research")
	if err != nil {
		t.Fatalf("parseStringListFlag returned error: %v", err)
	}
	want := []string{"reading", "research"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("expected %#v, got %#v", want, got)
	}
}

func TestParseStringListFlag_PreservesJSONArrayValues(t *testing.T) {
	got, err := parseStringListFlag(`["reading","research"]`)
	if err != nil {
		t.Fatalf("parseStringListFlag returned error: %v", err)
	}
	want := []any{"reading", "research"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("expected %#v, got %#v", want, got)
	}
}

func TestMergeSearchMatchWithObject_ReturnsUsefulSummary(t *testing.T) {
	fullSummary := "A long but useful description that must not be truncated because search results are the first place agents decide whether an object is relevant. Keeping the complete saved summary is more useful than forcing every agent to perform a second get call just to understand the result."
	match := json.RawMessage(`{"id":"obj_1","score":53.5}`)
	object := json.RawMessage(`{
		"id": "obj_1",
		"title": "Codex Skills Management Interface",
		"summary": ` + mustJSON(fullSummary) + `,
		"entityType": "Image",
		"source": {"url": "https://example.com/skills"},
		"tags": [{"name": "Codex"}, {"name": "ai skills"}],
		"blob": {"path": "private/blob"},
		"content": {"body": "too much content"}
	}`)

	got := mergeSearchMatchWithObject(match, object)

	var result map[string]any
	if err := json.Unmarshal(got, &result); err != nil {
		t.Fatalf("unmarshal result: %v", err)
	}
	for _, key := range []string{"id", "score", "title", "summary", "type", "url", "tags"} {
		if _, ok := result[key]; !ok {
			t.Fatalf("expected %q in summarized search result: %#v", key, result)
		}
	}
	for _, key := range []string{"blob", "content"} {
		if _, ok := result[key]; ok {
			t.Fatalf("did not expect verbose field %q in summarized search result: %#v", key, result)
		}
	}
	if result["summary"] != fullSummary {
		t.Fatalf("expected full summary to survive, got %#v", result["summary"])
	}
	tags, ok := result["tags"].([]any)
	if !ok || len(tags) != 2 || tags[0] != "Codex" || tags[1] != "ai skills" {
		t.Fatalf("expected full tag list to survive, got %#v", result["tags"])
	}
}

func TestSummarizeSearchMatch_FlattensDocumentMatches(t *testing.T) {
	match := json.RawMessage(`{
		"id": "obj_1",
		"score": 42,
		"document": {
			"id": "obj_1",
			"title": "A useful result",
			"source": {"url": "https://example.com"}
		}
	}`)

	got := summarizeSearchMatch(match)

	var result map[string]any
	if err := json.Unmarshal(got, &result); err != nil {
		t.Fatalf("unmarshal result: %v", err)
	}
	if result["title"] != "A useful result" {
		t.Fatalf("expected flattened title, got %#v", result)
	}
	if result["score"].(float64) != 42 {
		t.Fatalf("expected score to survive, got %#v", result)
	}
}

func TestSummarizeSearchMatch_PreservesHydrationFailure(t *testing.T) {
	match := json.RawMessage(`{
		"id": "obj_1",
		"score": 42,
		"hydration_status": "failed",
		"hydration_error": "GET /objects/obj_1 returned HTTP 404"
	}`)

	got := summarizeSearchMatch(match)

	var result map[string]any
	if err := json.Unmarshal(got, &result); err != nil {
		t.Fatalf("unmarshal result: %v", err)
	}
	if result["hydration_status"] != "failed" {
		t.Fatalf("expected hydration status to survive: %#v", result)
	}
	if result["hydration_error"] == "" {
		t.Fatalf("expected hydration error to survive: %#v", result)
	}
}

func TestOutputSearchResults_AppliesSelect(t *testing.T) {
	flags := &rootFlags{asJSON: true, selectFields: "id,title,score"}
	cmd := &cobra.Command{}
	var out bytes.Buffer
	cmd.SetOut(&out)
	results := []json.RawMessage{json.RawMessage(`{
		"id": "obj_1",
		"title": "Useful",
		"summary": "Hidden by select",
		"score": 1
	}`)}

	if err := outputSearchResults(cmd, flags, results, 10, DataProvenance{Source: "live"}); err != nil {
		t.Fatalf("outputSearchResults returned error: %v", err)
	}

	var envelope struct {
		Results []map[string]any `json:"results"`
	}
	if err := json.Unmarshal(out.Bytes(), &envelope); err != nil {
		t.Fatalf("unmarshal envelope: %v\n%s", err, out.String())
	}
	if _, ok := envelope.Results[0]["summary"]; ok {
		t.Fatalf("--select should remove summary: %#v", envelope.Results[0])
	}
	if envelope.Results[0]["title"] != "Useful" {
		t.Fatalf("expected selected title: %#v", envelope.Results[0])
	}
}

func TestFormatSearchHumanResults_ShowsFullSummaryAndTags(t *testing.T) {
	longSummary := "This saved object summary is deliberately longer than sixty characters because the human search renderer must show the full thought, not a clipped table cell."
	tags := []string{
		"research", "interface systems", "longform notes", "memory design",
		"search ranking", "agent handoff", "personal archive", "reference",
	}
	result := json.RawMessage(`{
		"id": "obj_1",
		"title": "Search renderer notes",
		"score": 87.25,
		"type": "note",
		"url": "https://example.com/search-renderer",
		"summary": ` + mustJSON(longSummary) + `,
		"tags": ` + mustJSON(tags) + `,
		"created": "2026-05-08T09:00:00Z",
		"modified": "2026-05-08T10:30:00Z",
		"hydration_error": "GET /objects/obj_1 returned HTTP 503"
	}`)

	var out bytes.Buffer
	if err := formatSearchHumanResults(&out, []json.RawMessage{result}); err != nil {
		t.Fatalf("formatSearchHumanResults returned error: %v", err)
	}
	got := out.String()

	for _, want := range []string{
		"Search renderer notes",
		"Score: 87.25",
		"Type: note",
		"URL: https://example.com/search-renderer",
		longSummary,
		strings.Join(tags, ", "),
		"Created: 2026-05-08",
		"Modified: 2026-05-08",
		"Hydration error: GET /objects/obj_1 returned HTTP 503",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("human search output missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "This saved object summary is deliberately longer than sixty charac...") {
		t.Fatalf("human search output used generic truncation:\n%s", got)
	}
}

func TestOutputSearchResults_AppliesCompactInMachineMode(t *testing.T) {
	flags := &rootFlags{compact: true}
	cmd := &cobra.Command{}
	var out bytes.Buffer
	cmd.SetOut(&out)
	results := []json.RawMessage{json.RawMessage(`{
		"id": "obj_1",
		"title": "Useful",
		"summary": "Kept by compact",
		"score": 1,
		"blob": {"path": "private/blob"}
	}`)}

	if err := outputSearchResults(cmd, flags, results, 10, DataProvenance{Source: "live"}); err != nil {
		t.Fatalf("outputSearchResults returned error: %v", err)
	}

	var envelope struct {
		Results []map[string]any `json:"results"`
	}
	if err := json.Unmarshal(out.Bytes(), &envelope); err != nil {
		t.Fatalf("unmarshal envelope: %v\n%s", err, out.String())
	}
	if envelope.Results[0]["summary"] != "Kept by compact" {
		t.Fatalf("--compact should preserve summary: %#v", envelope.Results[0])
	}
	if _, ok := envelope.Results[0]["blob"]; ok {
		t.Fatalf("--compact should remove verbose fields: %#v", envelope.Results[0])
	}
	if envelope.Results[0]["id"] != "obj_1" {
		t.Fatalf("expected compact id: %#v", envelope.Results[0])
	}
}

func TestSearchStatusEnabled_Suppression(t *testing.T) {
	tests := []struct {
		name      string
		flags     rootFlags
		stdoutTTY bool
		stderrTTY bool
		env       map[string]string
		want      bool
	}{
		{name: "human tty", stdoutTTY: true, stderrTTY: true, want: true},
		{name: "json", flags: rootFlags{asJSON: true}, stdoutTTY: true, stderrTTY: true},
		{name: "agent", flags: rootFlags{agent: true}, stdoutTTY: true, stderrTTY: true},
		{name: "compact", flags: rootFlags{compact: true}, stdoutTTY: true, stderrTTY: true},
		{name: "csv", flags: rootFlags{csv: true}, stdoutTTY: true, stderrTTY: true},
		{name: "quiet", flags: rootFlags{quiet: true}, stdoutTTY: true, stderrTTY: true},
		{name: "non tty stdout", stdoutTTY: false, stderrTTY: true},
		{name: "non tty stderr", stdoutTTY: true, stderrTTY: false},
		{name: "ci", stdoutTTY: true, stderrTTY: true, env: map[string]string{"CI": "true"}},
		{name: "term dumb", stdoutTTY: true, stderrTTY: true, env: map[string]string{"TERM": "dumb"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := searchStatusEnabled(&tt.flags, tt.stdoutTTY, tt.stderrTTY, func(key string) string {
				return tt.env[key]
			})
			if got != tt.want {
				t.Fatalf("searchStatusEnabled() = %t, want %t", got, tt.want)
			}
		})
	}
}
