// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSpacesObjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "objects",
		Short: "Manage objects",
	}

	cmd.AddCommand(newSpacesObjectsAddToSpaceCmd(flags))
	cmd.AddCommand(newSpacesObjectsRemoveFromSpaceCmd(flags))
	return cmd
}
