// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "convert content", Description: "Converts between plain text, Markdown, and mymind prose. Source and target formats must differ.", Group: "convert"},
	{Command: "entities get-entity", Description: "WIP/coming soon. The docs say type identifiers, property shapes, and this endpoint\nmay change before launch. Do not ship production integrations against this path yet.", Group: "entities"},
	{Command: "mymind-search search-objects", Description: "Search with Lucene-inspired syntax, optional semantic search, related-object matching,\nand Mastermind-only reranking.", Group: "mymind-search"},
	{Command: "objects create", Description: "Creates an object from exactly one of `url`, `content`, or multipart `blob`.\nDuplicate URL/content/blob saves return the existing object, refresh `bumped`,\nand respond with 200 instead of 201.", Group: "objects"},
	{Command: "objects delete", Description: "Soft-deletes an object. Deleted objects are recoverable for 30 days.", Group: "objects"},
	{Command: "objects get", Description: "Get an object", Group: "objects"},
	{Command: "objects list", Description: "Returns objects accessible to the authenticated key. If `q` is present, search\nsemantics and search credit costs apply. Deleted objects are excluded.", Group: "objects"},
	{Command: "objects update", Description: "Update object metadata", Group: "objects"},
	{Command: "objects blob get-object", Description: "Returns original uploaded bytes for single-blob objects. May return 302 to a signed CDN URL.", Group: "objects"},
	{Command: "objects content get-object", Description: "Returns text-based object content in native or requested format.", Group: "objects"},
	{Command: "objects content update-object", Description: "Full-replaces the content body of a Note object. Returns 422 for other object types.", Group: "objects"},
	{Command: "objects notes create-object", Description: "Appends a note. API stores up to 100 notes, but the app currently surfaces only `notes[0]`.", Group: "objects"},
	{Command: "objects notes delete-object", Description: "Delete an object note", Group: "objects"},
	{Command: "objects notes update-object", Description: "Full-replaces an existing note body.", Group: "objects"},
	{Command: "objects pin object", Description: "Pin an object", Group: "objects"},
	{Command: "objects pin unpin-object", Description: "Unpin an object", Group: "objects"},
	{Command: "objects restore object", Description: "Restore an object", Group: "objects"},
	{Command: "objects screenshot get-object", Description: "Returns screenshot bytes captured at save time. May return 302 to a signed CDN URL.", Group: "objects"},
	{Command: "objects spaces add-object", Description: "Adds one object to one or more spaces. Objects may belong to at most 100 spaces.", Group: "objects"},
	{Command: "objects tags add-object", Description: "Add tags to an object", Group: "objects"},
	{Command: "objects tags remove-object", Description: "Remove tags from an object", Group: "objects"},
	{Command: "objects thumbnail get-object", Description: "Get object thumbnail", Group: "objects"},
	{Command: "spaces create", Description: "Create a space", Group: "spaces"},
	{Command: "spaces delete", Description: "Deletes the space; objects inside are not deleted.", Group: "spaces"},
	{Command: "spaces get", Description: "Get a space", Group: "spaces"},
	{Command: "spaces list", Description: "List spaces", Group: "spaces"},
	{Command: "spaces update", Description: "Update a space", Group: "spaces"},
	{Command: "spaces objects add-to-space", Description: "Add an object to a space", Group: "spaces"},
	{Command: "spaces objects remove-from-space", Description: "Remove an object from a space", Group: "spaces"},
	{Command: "tags list", Description: "Tags are created implicitly when first used; there is no standalone create tag endpoint.", Group: "tags"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  mymind which "stale tickets"
  mymind which "bottleneck"
  mymind which --limit 1 "send message"
  mymind which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
