// Copyright 2026 nawwwal. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL         string    `toml:"base_url"`
	AuthHeaderVal   string    `toml:"auth_header"`
	AuthSource      string    `toml:"-"`
	AccessToken     string    `toml:"access_token"`
	RefreshToken    string    `toml:"refresh_token"`
	TokenExpiry     time.Time `toml:"token_expiry"`
	ClientID        string    `toml:"client_id"`
	ClientSecret    string    `toml:"client_secret"`
	Path            string    `toml:"-"`
	MymindSignedJwt string    `toml:"signed_jwt"`
	MymindKid       string    `toml:"kid"`
	MymindSecret    string    `toml:"secret"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://api.mymind.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("MYMIND_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "mymind", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("MYMIND_SIGNED_JWT"); v != "" {
		cfg.MymindSignedJwt = v
		cfg.AuthSource = "env:MYMIND_SIGNED_JWT"
	}
	if v := os.Getenv("MYMIND_KID"); v != "" {
		cfg.MymindKid = v
		cfg.AuthSource = "env:MYMIND_KID+MYMIND_SECRET"
	}
	if v := os.Getenv("MYMIND_SECRET"); v != "" {
		cfg.MymindSecret = v
		cfg.AuthSource = "env:MYMIND_KID+MYMIND_SECRET"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("MYMIND_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.MymindSignedJwt != "" {
		c.AuthSource = "env:MYMIND_SIGNED_JWT"
		return "Bearer " + c.MymindSignedJwt
	}
	if c.MymindKid != "" && c.MymindSecret != "" {
		if c.AuthSource == "" {
			c.AuthSource = "kid_secret"
		}
		return "mymind-signed-per-request"
	}
	if c.AccessToken != "" {
		c.AuthSource = "oauth2"
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) ClearTokens() error {
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.MymindSignedJwt = ""
	c.MymindKid = ""
	c.MymindSecret = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
